In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('fama_french.csv')
df.head()

date        gm      adbe       ora       flo  mkt_rf     smb     hml  \
0  2012-10-01  0.120879  0.049014  0.014934 -0.024281 -0.0176 -0.0116  0.0359   
1  2012-11-01  0.014902  0.017044 -0.032055  0.195531  0.0078  0.0064 -0.0084   
2  2012-12-01  0.113988  0.088703  0.046689 -0.004530  0.0118  0.0150  0.0351   
3  2013-01-01 -0.025668  0.003981  0.102697  0.155135  0.0557  0.0033  0.0096   
4  2013-02-01 -0.033464  0.039122 -0.038570  0.048363  0.0129 -0.0028  0.0011   

       rf  
0  0.0001  
1  0.0001  
2  0.0001  
3  0.0000  
4  0.0000

In [18]:
r = []
f_m = [1]
f_smb = [1]
f_hml = [1]
for i in range(5):
    r.append(df['gm'][i])
    f_m.append(df['mkt_rf'][i])
    f_smb.append(df['smb'][i])
    f_hml.append(df['hml'][i])


In [26]:
r_gm = np.array([r])
F = np.array([f_m,f_smb,f_hml])


In [27]:
F

array([[ 1.    , -0.0176,  0.0078,  0.0118,  0.0557,  0.0129],
       [ 1.    , -0.0116,  0.0064,  0.015 ,  0.0033, -0.0028],
       [ 1.    ,  0.0359, -0.0084,  0.0351,  0.0096,  0.0011]])

In [30]:
x1 = np.dot(np.transpose(F), F)
x2 = np.linalg.inv(x1)

In [33]:
x3 = np.dot(x2, np.transpose(F))
x4 = np.dot(x3,r_gm)

ValueError: shapes (6,3) and (1,5) not aligned: 3 (dim 1) != 1 (dim 0)

In [34]:
r_gm

array([[ 0.12087893,  0.01490208,  0.1139877 , -0.02566755, -0.03346422]])

In [35]:
x3

array([[  -0.58506332,   -0.72292468,    2.5678294 ],
       [ 152.14037919,  123.81296224, -147.21614892],
       [ 478.01522511,  531.88535247, -526.46216682],
       [  -9.9032    ,   24.83073333,  -42.97963333],
       [  15.4516    ,   -6.54036667,    3.30231667],
       [   8.        ,  -42.        ,   21.        ]])